### ISSUE TITLE
chore: reflect feedback on DateViewContainer

### ISSUE THREAD

**Issue by altenull** [oldiepuppie/apod#26]
**DateViewContainer**
* yy -> yyyy
* mm 그리고 dd 변수에서 숫자 0은 앞에 스트링으로 바로 넣어주기
* 코드에서 알 수 있는 내용을 주석으로 작성한 것은 주석을 지워주기

**Comment by oldiepuppie** [comment]
yy -> yyyy / 코드에서 알 수 있는 내용을 주석으로 작성한 것은 주석을 지워주기 /
